# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-service
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443  # listens on port 8443
  type: NodePort

