version: '3.5'
services:
  messagebus:
    container_name: messagebus
    build: .
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - "4000:50051"
    stdin_open: true
    tty: true